version: 2.1
jobs:
  build:
    docker:
      - image: 'accipiter7/waho:latest'
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'c2:64:78:d6:44:91:db:ef:f6:c0:21:03:61:c7:91:49'
       - run:
          name: Keyscan Github (HACK)
          command: | 
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Cloning Alpha
          command:  git clone -b thy --depth 1  git@github.com:Accipiter7/Alpha-1.git c
      - run:  
          name: Compilation
          command: bash /root/project/c/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - build
