name: flawfinder
on: [push]

jobs:
  build:
    name: flawfinder-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flawfinder-action 
        uses: deep5050/flawfinder-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
