name: Build & Test
on:
  push:
    branches: [ tmp ]
  pull_request:
    branches: [ tmp ]

jobs:

  build-test:
   
    runs-on: ubuntu-latest
    
    steps:
   
    - uses: actions/checkout@v2.1.0

      
    - name: Merge Conflict Finder
      uses: olivernybroe/action-conflict-finder@v1.1
 
    - name: Clang Code Formatter
      uses: ivanludvig/clang-format-action@v1.4
 
        
