name: flawfinder
on: [push]

jobs:
  build:
    name: flawfinder-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform security scan
      uses: triat/terraform-security-scan@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
